# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f73a2723751784e12c3a9b06c7e5b1d9ba51e606973c75b5837b63a4e93dcf85c3e56a4eccaf7456e026ffc905dc4334437258bd723a3fd842e11504e29d7b52

test:
  secret_key_base: 9f7e815290c3c134b931e0582dd12a672a78b9dadc6ae4d813ef7c3f532c5d4d0c7f9294d23cccc562281d0b3ee2f470443de10e79701d7e53c3df1ee4291c25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
